### ISSUE TITLE
Ended homework

### ISSUE THREAD

**Issue by vickyantre** [Artinov/home-work-10-vickyantre#1]
Somehow my list lose class "list-group-item" if i clink button to mark all tasks. It begins when i tried to refactor my code.

And another problem - when i do some changes the same button my app doesn't remember it after pressing F5.

**Comment by eko24ive** [comment]
Hi @vickyantre.
Reason why your code is losing `.list-group-item` is lays on 72 line https://github.com/Artinov/home-work-10-vickyantre/blob/master/to_do.js#L72
You've missing space there.

Could you please specify what change your app is not saving ?

**Comment by vickyantre** [comment]
Saving work already. It hadn`t worked when i pressed AllMarked button and all task was completed.

**Comment by eko24ive** [comment]
Well, I can see now, that this feature works ok.
@vickyantre, can you reproduce this bug ?

**Comment by vickyantre** [comment]
I do not know how.

**Comment by eko24ive** [comment]
If you said:
 > It hadn`t worked when i pressed AllMarked button

Then you can try press this button again, reload page, and see if your app save state of todo items.
